### ISSUE TITLE
Duplicação de código entre as classes Resource

### ISSUE THREAD

**Issue by manoelcampos** [silvioantonio/inf-money#1]
As classes como `CategoriaResource` e `PessoaResource` estão basicamente expondo operações CRUD. Para reduzir a duplicação de código, você pode criar uma classe abstrata (que não necessariamente terá métodos abstratos, apenas para impedir instanciação direta, pois ela sozinha não faz sentido) como `AbstractCrudResource`. Tal classe deve ser genérica, para permitir indicar qual o tipo de objetos de negócio que as subclasses dela trabalharão.

**Comment by silvioantonio** [comment]
Working on it...
Estou verificando como implementar de forma mais legivel...

**Comment by manoelcampos** [comment]
Great 😄

**Comment by silvioantonio** [comment]
Problema resolvido rsrs

**Comment by manoelcampos** [comment]
Vc pode fechar uma issue automaticamente, apenas colocando na mensagem do commit "Close #NUMERO_DA_ISSUE". Assim, o GitHub vai mostrar aqui qual commit resolveu o problema.

**Comment by manoelcampos** [comment]
Olhei o último commit. Ficou ótimo 😄
